config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :home, only: [:index]
  get 'home/swipe', to: 'home#swipe'
  post 'home/swipe_in', to: 'home#swipe_in'
  post 'home/swipe_out', to: 'home#swipe_out'
  post 'home/time_sheet', to: 'home#time_sheet'
  post 'home/time_off', to: 'home#time_off'

  resources :users do
    resources :timesheets, only: [:index]
    resources :shifts, only: [:create, :edit, :update, :destroy]
  end
  resources :requests, only: [:index, :new, :create, :edit, :update]
  post 'requests/:id/update_status', to: 'requests#update_status', as: 'update_status_request'
  resources :positions, except: [:show]
  resources :divisions, except: [:show]
  resources :unions, except: [:show]
end

app/models/union.rb
class Union < ApplicationRecord
  has_many :positions, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/controllers/unions_controller.rb
class UnionsController < ApplicationController
  before_action :get_union, only: [:edit, :update, :destroy]

  def index
    @unions = Union.all
  end

  def new
    @union = Union.new
  end


  def create
    @union = Union.new(union_params)

    if @union.save
      flash[:success] = 'Union Successfully Created'
      redirect_to unions_path
    else
      flash[:warning] = @union.errors.full_messages
      redirect_to action: :new
    end
  end

  def update
    if @union.update(union_params)
      flash[:success] = 'Union Successfully Updated'
      redirect_to unions_path
    else
      flash[:warning] = 'Union Could Not Be Updated'
      redirect_to action: :edit
    end
  end

  def destroy
    @union.destroy
    flash[:success] = "Union Successfully Deleted"
    redirect_to unions_path
  end

  private

  def get_union
    @union = Union.find(params[:id])
  end

  def union_params
    params.require(:union).permit(:name)
  end
end

app/views/unions/edit.html.haml
%h1 Edit Union
= form_for @union, html: { class: 'form-horizontal' } do |f|
  .form-group
    .control-label.col-xs-2
      = f.label :name, 'Name'
    .col-xs-5
      = f.text_field :name, class: 'form-control',
                            value: @union.name,
                            required: true
  .form-group
    .col-xs-offset-2.col-xs-5
      = f.submit 'Update', class: 'btn btn-primary btn-md'
      = link_to 'Cancel', unions_path, class: 'btn btn-default btn-md'

app/views/unions/index.html.haml
%h1 Unions

%h2
  = link_to 'New Union', new_union_path, class: 'btn btn-primary btn-md'

%table.table.table-striped.table-bordered.table-hover
  %tr
    %th Name
    %th.min-width Actions
  - @unions.each do |union|
    %tr
      %td
        = union.name
      %td.min-width.pull
        = link_to content_tag(:span, nil, class: 'glyphicon glyphicon-edit')+' Edit',
          edit_union_path(union),
          class: 'btn btn-primary'
        = link_to content_tag(:span, nil, class: 'glyphicon glyphicon-trash')+' Delete',
          union_path(union),
          method: :delete,
          data: { confirm: 'Are you sure? Deleting this Union will also delete all Positions that belong to it.' },
          class: 'btn btn-danger'

app/views/unions/new.html.haml
%h1 New Union
= form_for @union, html: { class: 'form-horizontal' } do |f|
  .form-group
    .control-label.col-xs-2
      = f.label :name, 'Name'
    .col-xs-5
      = f.text_field :name, class: 'form-control', required: true
  .form-group
    .col-xs-offset-2.col-xs-5
      = f.submit 'Create', class: 'btn btn-primary btn-md'
      = link_to 'Cancel', unions_path, class: 'btn btn-default btn-md'