config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :home, only: [:index]
  get 'home/swipe', to: 'home#swipe'
  post 'home/swipe_in', to: 'home#swipe_in'
  post 'home/swipe_out', to: 'home#swipe_out'
  post 'home/time_sheet', to: 'home#time_sheet'
  post 'home/time_off', to: 'home#time_off'

  resources :users do
    resources :timesheets, only: [:index]
    resources :shifts, only: [:create, :edit, :update, :destroy]
  end
  resources :requests, only: [:index, :new, :create, :edit, :update]
  post 'requests/:id/update_status', to: 'requests#update_status', as: 'update_status_request'
  resources :positions, except: [:show]
  resources :divisions, except: [:show]
  resources :unions, except: [:show]
end

app/models/position.rb
class Position < ApplicationRecord
  has_many :users, dependent: :nullify
  belongs_to :union

  validates :name, presence: true, uniqueness: { scope: :union }
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  before_action :get_position, only: [:edit, :update, :destroy]

  def index
    @positions = Position.all
  end

  def new
    @position = Position.new
    @unions = Union.all
  end

  def create
    @position = Position.new(position_params)

    if @position.save
      flash[:success] = 'Position Successfully Created'
      redirect_to positions_path
    else
      flash[:warning] = @position.errors.full_messages
      redirect_to action: :new
    end
  end

  def edit
    @unions = Union.all
  end

  def update
    if @position.update(position_params)
      flash[:success] = 'Position Successfully Updated'
      redirect_to positions_path
    else
      flash[:warning] = 'Position Could Not Be Updated'
      redirect_to action: :edit
    end
  end

  def destroy
    @position.destroy
    flash[:success] = "Position Successfully Deleted"
    redirect_to positions_path
  end

  private

  def get_position
    @position = Position.find(params[:id])
  end

  def position_params
    params.require(:position).permit(:name, :union_id)
  end
end

app/views/positions/edit.html.haml
%h1 Edit Position
= form_for @position, html: { class: 'form-horizontal' } do |f|
  .form-group
    .control-label.col-xs-2
      = f.label :name, 'Name'
    .col-xs-5
      = f.text_field :name, class: 'form-control',
                            value: @position.name,
                            required: true
  .form-group
    .control-label.col-xs-2
      = f.label :union_id, 'Union'
    .col-xs-5
      = f.select :union_id, @unions.collect{ |u| [u.name, u.id] }, {},
                                class: 'selectpicker form-control',
                                include_blank: true,
                                required: true,
                                selected: @position.union_id
  .form-group
    .col-xs-offset-2.col-xs-5
      = f.submit 'Update', class: 'btn btn-primary btn-md'
      = link_to 'Cancel', positions_path, class: 'btn btn-default btn-md'

app/views/positions/index.html.haml
%h1 Positions

%h2
  = link_to 'New Position', new_position_path, class: 'btn btn-primary btn-md'

%table.table.table-striped.table-bordered.table-hover
  %tr
    %th Name
    %th Union
    %th.min-width Actions
  - @positions.each do |position|
    %tr
      %td
        = position.name
      %td
        = position.union.try :name
      %td{class: 'min-width', align: 'center'}
        = link_to content_tag(:span, nil, class: 'glyphicon glyphicon-edit')+' Edit',
          edit_position_path(position),
          class: 'btn btn-primary'
        = link_to content_tag(:span, nil, class: 'glyphicon glyphicon-trash')+' Delete',
          position_path(position),
          method: :delete,
          data: { confirm: 'Are you sure?' },
          class: 'btn btn-danger'

app/views/positions/new.html.haml
%h1 New Position
= form_for @position, html: { class: 'form-horizontal' } do |f|
  .form-group
    .control-label.col-xs-2
      = f.label :name, 'Name'
    .col-xs-5
      = f.text_field :name, class: 'form-control', required: true
  .form-group
    .control-label.col-xs-2
      = f.label :union_id, 'Union'
    .col-xs-5
      = f.select :union_id, @unions.collect{ |u| [u.name, u.id] }, {},
                               class: 'selectpicker form-control',
                               include_blank: true
  .form-group
    .col-xs-offset-2.col-xs-5
      = f.submit 'Create', class: 'btn btn-primary btn-md'
      = link_to 'Cancel', positions_path, class: 'btn btn-default btn-md'