config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :home, only: [:index]
  get 'home/swipe', to: 'home#swipe'
  post 'home/swipe_in', to: 'home#swipe_in'
  post 'home/swipe_out', to: 'home#swipe_out'
  post 'home/time_sheet', to: 'home#time_sheet'
  post 'home/time_off', to: 'home#time_off'

  resources :users do
    resources :timesheets, only: [:index]
    resources :shifts, only: [:create, :edit, :update, :destroy]
  end
  resources :requests, only: [:index, :new, :create, :edit, :update]
  post 'requests/:id/update_status', to: 'requests#update_status', as: 'update_status_request'
  resources :positions, except: [:show]
  resources :divisions, except: [:show]
  resources :unions, except: [:show]
end

app/views/layouts/shared/_footer.html.haml
.footer
  .container
    %p
      This site is maintained by UMass Amherst Parking Services
      %br/
      413.577.PARK |
      %a{href: "https://parking.umass.edu/", rel: "nofollow"} Public Home Page
      |
      %a{href: "https://parking-flex.admin.umass.edu/PowerPark/login.aspx?target=%2fPowerPark%2f"} T2 Flex
      |
      %a{href: "mailto:transportationit@umass.edu?Subject=Issue:", target: "_top"} Submit Track-It! Ticket
      %br/
      © #{Date.today.year}
      %a{href: "http://www.umass.edu/", rel: "nofollow"} University of Massachusetts Amherst
      |
      %a{href: "http://www.umass.edu/umhome/policies/", rel: "nofollow"} Site Policies

app/views/layouts/shared/_header.html.haml
.page-header
  .container
    %a{href: "http://umass.edu/"}= image_tag("umass-wordmark-wht.png", alt: "UMass Amherst", width: "175", height: "23")
    %form#gs.pull-right{action: "http://googlebox.oit.umass.edu/search", method: "get", name: "gs", onsubmit: "if (this.q.value=='Search UMass Amherst') return false;", style: "margin: 0; padding: 0"}
      %div
        %label{for: "q", style: "display:inline-block"}
          %input#q{name: "q", onblur: "if (this.value=='') this.value='Search UMass Amherst'", onfocus: "if (this.value=='Search UMass Amherst') this.value=''", size: "22", style: "font-size:11px; font-family:Verdana,sans-serif; padding-left:2px; width:150px", type: "text", value: "Search UMass Amherst"}/
        %input{name: "sa", style: "font-size: 11px; font-family: Verdana, sans-serif;", type: "submit", value: "Go"}/
        %input{name: "site", type: "hidden", value: "default_collection"}/
        %input{name: "client", type: "hidden", value: "default_frontend"}/
        %input{name: "proxystylesheet", type: "hidden", value: "default_frontend"}/
        %input{name: "output", type: "hidden", value: "xml_no_dtd"}/
.sub-header
  .container
    = link_to image_tag("parking-logo.png", alt: "UMass Parking Services"), "https://parking.umass.edu/", class: "pull-left"

app/views/layouts/shared/_navbar.html.haml
%nav.navbar.main.navbar-default
  .container
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      = link_to "Time Machine", root_path, class: "navbar-brand"
      %button.main.navbar-toggle.collapsed{"data-target" => "#navbar-collapse-1",
                                           "data-toggle" => "collapse",
                                            type: "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
    / Collect the nav links, forms, and other content for toggling
    #navbar-collapse-1.collapse.navbar-collapse
      %ul.main.nav.navbar-nav
        %li.dropdown
          %a.dropdown-toggle{"aria-expanded" => "false",
                             "data-toggle" => "dropdown",
                              href: "#",
                              role: "button"}
            Admin
            %span.caret
          %ul.dropdown-menu{role: "menu"}
            %li
              = link_to 'Users', users_path
            %li
              = link_to 'Divisions', divisions_path
            %li
              = link_to 'Positions', positions_path
            %li
              = link_to 'Unions', unions_path
            %li
              = link_to 'Requests', requests_path