config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :home, only: [:index]
  get 'home/swipe', to: 'home#swipe'
  post 'home/swipe_in', to: 'home#swipe_in'
  post 'home/swipe_out', to: 'home#swipe_out'
  post 'home/time_sheet', to: 'home#time_sheet'
  post 'home/time_off', to: 'home#time_off'

  resources :users do
    resources :timesheets, only: [:index]
    resources :shifts, only: [:create, :edit, :update, :destroy]
  end
  resources :requests, only: [:index, :new, :create, :edit, :update]
  post 'requests/:id/update_status', to: 'requests#update_status', as: 'update_status_request'
  resources :positions, except: [:show]
  resources :divisions, except: [:show]
  resources :unions, except: [:show]
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :check_invalid_swipe, only: %i[swipe_in swipe_out
                                               time_sheet time_off]

  def index
    session.delete(:swipe_id)
  end

  def swipe
    @form_path = if params[:redirect] == 'swipe_in'
                   home_swipe_in_path
                 elsif params[:redirect] == 'swipe_out'
                   home_swipe_out_path
                 elsif params[:redirect] == 'time_sheet'
                   home_time_sheet_path
                 elsif params[:redirect] == 'time_off'
                   home_time_off_path
                 else
                   home_index_path
                 end
  end

  def swipe_in
    shift_params = {
      user_id: @current_user.id,
      start_time: Time.now
    }

    create_shift(shift_params)
  end

  def swipe_out
    shift_params = {
      user_id: @current_user.id,
      end_time: Time.now
    }

    today_shifts = @current_user.shifts.where(start_time: Date.today..(Date.today + 1))
    last_shift = today_shifts.select { |s| s[:end_time].nil? }.last
    # Last shift exists, add an end time
    if last_shift.present?
      update_shift(last_shift, shift_params)
    # Last shift does not exist, create a new shift with just an end time
    else
      create_shift(shift_params)
    end
  end

  def time_sheet
    redirect_to user_timesheets_path(@current_user, date: Date.today)
  end

  def time_off
    redirect_to new_request_path
  end

  private

  def check_invalid_swipe
    if @current_user.nil?
      flash.now[:warning] = 'Invalid id. Try swiping again or contact IT.'
      render :swipe and return
    end
  end

  def create_shift(shift_params)
    shift = Shift.new(shift_params)
    if shift.save
      flash[:success] = 'Shift successfully created'
    else
      flash[:warning] = shift.errors.full_messages
    end
    redirect_to user_timesheets_path(@current_user)
  end

  def update_shift(shift, shift_params)
    if shift.update(shift_params)
      flash[:success] = 'Shift successfully updated'
    else
      flash[:warning] = shift.errors.full_messages
    end
    redirect_to user_timesheets_path(@current_user)
  end
end

app/views/home/index.html.haml
%h1 Welcome to Kronos!

= link_to 'Swipe In', home_swipe_path(redirect: 'swipe_in'), class: 'btn btn-default btn-xlg'
= link_to 'Swipe Out', home_swipe_path(redirect: 'swipe_out'), class: 'btn btn-default btn-xlg'
= link_to 'Time Sheet', home_swipe_path(redirect: 'time_sheet'), class: 'btn btn-default btn-xlg'
= link_to 'Time Off', home_swipe_path(redirect: 'time_off'), class: 'btn btn-default btn-xlg'

app/views/home/swipe.html.haml
%h1{ class: 'swipe-clock' }
  - if params[:redirect] == 'swipe_in'
    Swipe In
  - elsif params[:redirect] == 'swipe_out'
    Swipe Out
  - elsif params[:redirect] == 'time_sheet'
    Swipe to view time sheet
  - elsif params[:redirect] == 'time_off'
    Swipe to request time off

%h2{ id: 'home-swipe-clock-date', class: 'swipe-clock' }
%h2{ id: 'home-swipe-clock-time', class: 'swipe-clock' }

= form_tag @form_path, class: 'swipe-clock' do
  = hidden_field_tag :redirect, params[:redirect]
  .col-xs-offset-4.col-xs-4
    = password_field_tag :swipe_id, nil, autofocus: true, class: 'form-control'